import type { Metadata } from "next";
import { EB_Garamond } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";



export const metadata: Metadata = {
  title: "AI-Virtual-Staging",
  description: "Generated by create next app",
};


const garamond = EB_Garamond({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"]
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${garamond.className} antialiased min-h-screen`}
      >
        <Toaster
          position="bottom-right"
        />
        {children}
      </body>
    </html>
  );
}
