import Image from 'next/image'
import React from 'react'

const clients = [
    "/home/client1.jpg", "/home/client2.jpg", "/home/client3.jpg", "/home/client4.jpg"
]

const images = [
    "/gallery/image7.jpg",
    "/gallery/image8.jpg",
    "/gallery/image9.jpg",
    "/gallery/image10.jpg",
    "/gallery/image11.jpg",
    "/gallery/image12.jpg",
    "/gallery/image13.jpg",
    "/gallery/image14.jpg",
    "/gallery/image15.jpg",
    "/gallery/image16.jpg",
    "/gallery/image17.jpg",
    "/gallery/image18.jpg",
    "/gallery/image19.jpg",
    "/gallery/image20.jpg",
    "/gallery/image21.jpg",
    "/gallery/image22.jpg",
]

const GallerySection = () => {
    return (
        <section className="w-full px-4 sm:px-6 lg:px-20 3xl:p-16 mt-14">
            <h1 className="text-center text-[32px] sm:text-[40px] md:text-[60px] lg:text-[80px] font-normal">
                More designs
            </h1>
            <p className="text-black opacity-80 text-center text-lg font-normal md:text-[32px] mt-4 max-w-4xl mx-auto">
                Sharing all the designs that our community members have generated by using our AI-models
            </p>
            <div className='flex justify-center items-center mt-4'>
                <div className="flex justify-center items-center rounded-xl border border-dashed border-black px-5 py-2">
                    {clients.map((url, index) => (
                        <Image
                            key={index}
                            className='rounded-full -ml-1'
                            width={30}
                            height={30}
                            src={url}
                            alt='logo'
                        />
                    ))}
                </div>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 my-25">
                {images.map((src, index) => (
                    <div key={index} className="w-full h-[320px] relative rounded-xl overflow-hidden">
                        <Image
                            src={src}
                            alt={`Gallery image ${index + 1}`}
                            fill
                            className="object-cover"
                        />
                    </div>
                ))}
            </div>
        </section>
    )
}

export default GallerySection
